version: "3.7"

services:
  mongodb:
    container_name: "container-mongodb"
    image: mongo
    volumes:
      - ./.docker/mongodb:/data/db
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: "always"
    networks:
      - default