version: "3.7"

services:
  mongodb:
    container_name: "container-mongodb"
    image: mongo
    volumes:
      - ./.docker/mongodb:/data/db
    ports: 
      - "27017:27017"
    restart: "always"
    networks:
      - default